### ISSUE TITLE
Put down the issues here

### ISSUE THREAD

**Issue by Sly-Cloud** [Sly-Cloud/portfolio-project#5]
Please be kind to add the issues here.

**Comment by NJ-2020** [comment]
Hi Adon,

The background image banner of your web could have better if it was smaller size.
In the About myself section, the languages should be on the right side.

Great works in general.

Regards 
Novell

**Comment by alexander16108** [comment]
👍🏾 Hi Adon,

   so far I can't find any issue with your desktop version the code looks easy to read and understand 
  
  in General great job on the effort you put in 

Regards
Alex

**Comment by Sly-Cloud** [comment]
> Hi Adon,
> 
> The background image banner of your web could have better if it was smaller size.
> In the About myself section, the languages should be on the right side.
> 
> Great works in general.
> 
> Regards
> Novell

Thanks Novel, I will have a look

**Comment by Sly-Cloud** [comment]
> 👍🏾 Hi Adon,
> 
> so far I can't find any issue with your desktop version the code looks easy to read and understand
> 
> in General great job on the effort you put in
> 
> Regards
> Alex

That's fine Alex. Please, make sure to let me where you detect one
